__author__ = 'odoo'

import inherit_product_category
import procur_request_link
import inherit_purchase_order
import purchase_setting
import inherit_stock_picking
import quotation_comparison_form
import inherit_purchase_tenders
import tracking_approval
import mapping_department_to_product