__author__ = 'odoo'

import procur_request_link
import procur_good_request
import procur_good_manage
import inherit_purchase_order
import purchase_setting
import inherit_stock_picking
import quotation_comparison_form
import inherit_purchase_tenders
import procur_good_returns
import tracking_approval
